=== picslITK/ITK4_topics/Documentation/Migration/ITKMigration.dtd
<!ELEMENT Change ( Title, Author*, Date*, Description, SampleCode*, Gerrit-ChangeId, FileList, MigrationFix-Automatic*, MigrationFix-Manual* ) >

<!ELEMENT Description ( #PCDATA ) >

<!ELEMENT FileList ( #PCDATA ) >

<!ELEMENT Gerrit-ChangeId ( #PCDATA ) >

<!ELEMENT MigrationFix-Automatic ( Old, New ) >

<!ELEMENT MigrationFix-Manual ( Old, New ) >

<!ELEMENT New ( #PCDATA ) >

<!ELEMENT Old ( #PCDATA ) >

<!ELEMENT SampleCode ( Old*, New* ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Author ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

=== picslITK/ITK4_topics/Documentation/Migration/PolygonGroupOrientationMovedToPolygonSpatialObject.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** PolygonGroupOrientationMovedToPolygonSpatialObject.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      PolygonGroupOrientation Moved To PolygonSpatialObject
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      GaÃ«tan Lehmann
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-03-01
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      The enum itk::PolygonGroupOrientation, which was used only in itk::PolygonSpatialObject,
      has been moved in itk::PolygonSpatialObject.

      Wrapping an enum nested in a namespace and not in a class is quite
      difficult with the current wrapping system. It leads to using a &quot;using
      namespace ::itk&quot; which introduce some ambiguities in the definition of
      some types, like uintptr_t. msvc8 generates a build error in that case.
      As a consequence, enum directly in the itk namespace should be avoided.
      Enums inside a class and enums inside their own namespace are OK.

    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        #include &quot;itkPolygonGroupOrientation.h&quot;
      </Old>

      <New>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I3671478e408d3c40dea3bc9f62247c72157b181e
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/SpatialObject/itkPolygonGroupOrientation.h
      Code/SpatialObject/itkPolygonSpatialObject.h
      Code/SpatialObject/itkPolygonSpatialObject.txx
      Testing/Code/SpatialObject/itkSpatialObjectHeaderTest.cxx
      Wrapping/WrapITK/Libraries/SpatialObject/itkPolygonGroupOrientation.wrap
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/UseImageSpacingDefaultToOn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">

<!--**
** UseImageSpacingDefaultToOn.xml
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Use Image Spacing Default To On
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Hans Johnson
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-09-17
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      <![CDATA[
      The default behavior of filters should respect
      the physical space characteristics of an image.
      The end user will need to explicitly request
      to ignore image space (usually for performance
      reasons under well controlled conditions).
      ]]>
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        FiniteDifferenceImageFilter::Pointer pFD = FiniteDifferenceImageFilter::New();
        DisplacementFieldJacobianDeterminantFilter::Pointer pDFJD = DisplacementFieldJacobianDeterminantFilter::New();
        VectorGradientMagnitudeImageFilter::Pointer pVGMI = VectorGradientMagnitudeImageFilter::New();
        ]]>
      </Old>

      <New>
        <![CDATA[
        FiniteDifferenceImageFilter::Pointer pFD = FiniteDifferenceImageFilter::New();
        pFD->SetUseImageSpacing(false);
        DisplacementFieldJacobianDeterminantFilter::Pointer pDFJD = DisplacementFieldJacobianDeterminantFilter::New();
        pDFJD->SetUseImageSpacing(false);
        VectorGradientMagnitudeImageFilter::Pointer pVGMI = VectorGradientMagnitudeImageFilter::New();
        pVGMI->SetUseImageSpacing(false);
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I54a7f519321ba3db49fbd334bad7ca0a74a86a10
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.hxx
      Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.hxx
      Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
    </FileList>

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/MoveGetSetLengthMeasurementVectorTraits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--***************************************************************************
**
** MoveGetSetLengthMeasurementVectorTraits.xml
**
** This file provides a sample of an ITKv4 Migration guide XML document. The
** goal of these documents is to encode all information about changes to the
** ITK API between the v3.X releases and v4.0. Each migration document consists
** of a single <Change> element and a set of associated child elements. The
** <Change> element has a set of required child elements and a set of
** additional optional child elements which can be used to automatically
** identify locations in user code where the API change will mandate updates.
** In the case of simple changes, these rules can be used to automatically fix
** user code with the migration tool.
**
** REQUIRED CHILD ELEMENTS:
**
**    - <Description>: English description of what changes were made along with
**      rational for making them.
**
**    - <SampleCode>: Code snippet either manually written or automatically
**      harvested from the patch's changes that illustrates how to update the
**      API from the old version to the new version. This element must contain
**      two child elements, <Old> and <New>. As their names suggest, these two
**      elements contain the snippets of old API code and new API code.
**
**    - <FileList>: A list of all files that were changed in association with
**      the API change. File names should be specified relative to the base
**      source directory for ITK.
**
**    - <Gerrit-ChangeId>: This element links the API change to the Gerrit
**      entry used to review the change.
**
** OPTIONAL CHILD ELEMENTS:
**
**    - <ApplicationFixLink>: A link to git changes made when fixing
**      sequestered applications that broke due to the API change.
**
**    - <MigrationFix-Automatic>: A rule for the migration tool that can
**      automatically fix errors in user code. The current list of automatic
**      fix types is:
**
**      - "FileRename": Find and replace the file name with the new one. Must
**        include <Old> and <New> child elements.
**
**      - "ClassRename": Find and replace the name of a class. Must include
**        <Old> and <New> child elements.
**
**      - "ClassMove": Include the new location of the class. Must include
**        <Old> and <New> child elements. Will warn the user that the old
**        include file may be able to be removed but will not automatically
**        remove it.
**
**      - "MethodRename": Find and replace the name of the method. Must include
**        <Old> and <New> child elements.
**
**      - "MethodMove": Find and replace the name of a method. Only works if
**        the method's signature hasn't changed. Must include <Old> and <New>
**        child elements.
**
**      - "NamespaceChange": Find object from the old namespace and update its
**        namespace. This may not fix instances where "using namespace" is used
**        so the migration tool should warn the user wherever the object's
**        signature is found without a namespace attached. Must include <Old>
**        and <New> child elements.
**
**    - <MigrationFix-Manual>: A rule for the migration tool that can not be
**      automatcally fixed, but can be automatically identified. These rules
**      will cause the migration tool to flag a section of the code for
**      revision. The current type list is:
**
**      - "MethodRefactor": Flag the user anywhere the changed method is
**        called. Should be used any time a method's signature changes. Must
**        include an <Old> child element.
**
**      - "GeneralRefactor": Flag the user anywhere that the text specified in
**        the <Old> child element is found.
**
****************************************************************************-->

<Change>
  <!--**
  ** Title for the online migration page
  **-->
  <Title>
    Move Get Set Length Measurement Vector Traits
  </Title>
  <!--
  ** English language description of what was changed and why
  **-->
  <Description>
  In an attempt to consolidate the numeric traits api, we are moving all
  functionality from Code/Numerics/Statistics/itkMeasurementVectorTraits.h into
  the individual NumericTraits files in Code/Common.
  </Description>

  <!--
  ** Sample code to illustrate the fix process
  **-->
  <SampleCode>
    <Old>
    MeasurementVectorType mv;
    MeasurementVectorTraits::SetLength( mv, 3 );
    unsigned int length = MeasurementVectorTraits::GetLength( mv );
    </Old>

    <New>
    <![CDATA[
    MeasurementVectorType mv;
    NumericTraits<MeasurementVectorType>::SetLength( mv, 3 );
    unsigned int length = NumericTraits<MeasurementVectorType>::GetLength( mv );
    ]]>
    </New>
  </SampleCode>

  <!--
  ** The asociated Gerrit entry for this API change
  **-->
  <Gerrit-ChangeId>
  Ie78170c85c29a5d030e5ab605610878fe67d75c2
  </Gerrit-ChangeId>

  <!--
  ** List of all files that were changed (might be automatically populated by
  ** git hook?)
  **-->
  <FileList>
  Code/Common/itkNumericTraitsArrayPixel.h
  Code/Common/itkNumericTraitsCovariantVectorPixel.h
  Code/Common/itkNumericTraitsDiffusionTensor3DPixel.h
  Code/Common/itkNumericTraitsFixedArrayPixel.h
  Code/Common/itkNumericTraitsPointPixel.h
  Code/Common/itkNumericTraitsRGBAPixel.h
  Code/Common/itkNumericTraitsRGBPixel.h
  Code/Common/itkNumericTraitsStdVector.h
  Code/Common/itkNumericTraitsTensorPixel.h
  Code/Common/itkNumericTraitsVariableLengthVectorPixel.h
  Code/Common/itkNumericTraitsVectorPixel.h
  Code/Numerics/Statistics/itkCovarianceSampleFilter.txx
  Code/Numerics/Statistics/itkDistanceMetric.h
  Code/Numerics/Statistics/itkDistanceMetric.txx
  Code/Numerics/Statistics/itkEuclideanDistanceMetric.txx
  Code/Numerics/Statistics/itkEuclideanSquareDistanceMetric.txx
  Code/Numerics/Statistics/itkExpectationMaximizationMixtureModelEstimator.txx
  Code/Numerics/Statistics/itkGaussianMembershipFunction.txx
  Code/Numerics/Statistics/itkGaussianMixtureModelComponent.txx
  Code/Numerics/Statistics/itkImageToListSampleFilter.txx
  Code/Numerics/Statistics/itkKdTree.txx
  Code/Numerics/Statistics/itkKdTreeBasedKmeansEstimator.h
  Code/Numerics/Statistics/itkKdTreeBasedKmeansEstimator.txx
  Code/Numerics/Statistics/itkKdTreeGenerator.txx
  Code/Numerics/Statistics/itkListSample.txx
  Code/Numerics/Statistics/itkMahalanobisDistanceMetric.txx
  Code/Numerics/Statistics/itkManhattanDistanceMetric.txx
  Code/Numerics/Statistics/itkMeasurementVectorTraits.h
  Code/Numerics/Statistics/itkMembershipFunctionBase.h
  Code/Numerics/Statistics/itkSample.h
  Code/Numerics/Statistics/itkSampleToHistogramFilter.txx
  Code/Numerics/Statistics/itkScalarImageToHistogramGenerator.txx
  Code/Numerics/Statistics/itkStandardDeviationPerComponentSampleFilter.txx
  Code/Numerics/Statistics/itkStatisticsAlgorithm.txx
  Code/Numerics/Statistics/itkWeightedCentroidKdTreeGenerator.txx
  Code/Numerics/Statistics/itkWeightedCovarianceSampleFilter.txx
  Testing/Code/Numerics/Statistics/CMakeLists.txt
  Testing/Code/Numerics/Statistics/itkDistanceToCentroidMembershipFunctionTest.cxx
  Testing/Code/Numerics/Statistics/itkEuclideanDistanceMetricTest.cxx
  Testing/Code/Numerics/Statistics/itkEuclideanSquareDistanceMetricTest.cxx
  Testing/Code/Numerics/Statistics/itkGaussianMembershipFunctionTest.cxx
  Testing/Code/Numerics/Statistics/itkListSampleTest.cxx
  Testing/Code/Numerics/Statistics/itkMahalanobisDistanceMetricTest.cxx
  Testing/Code/Numerics/Statistics/itkManhattanDistanceMetricTest.cxx
  Testing/Code/Numerics/Statistics/itkMembershipSampleTest1.cxx
  Testing/Code/Numerics/Statistics/itkMembershipSampleTest2.cxx
  Testing/Code/Numerics/Statistics/itkMembershipSampleTest3.cxx
  Testing/Code/Numerics/Statistics/itkMembershipSampleTest4.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest1.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest2.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest3.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest4.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest5.cxx
  Testing/Code/Numerics/Statistics/itkSampleClassifierFilterTest6.cxx
  Testing/Code/Numerics/Statistics/itkStatisticsTests.cxx
  Testing/Code/Numerics/Statistics/itkWeightedCentroidKdTreeGeneratorTest8.cxx
  Testing/Code/Numerics/Statistics/itkWeightedCentroidKdTreeGeneratorTest9.cxx
  Testing/Code/Numerics/Statistics/itkWeightedCovarianceSampleFilterTest2.cxx
  </FileList>



  <!--
  ** Migration guide rules
  **-->
  <MigrationFix-Manual>
    <Old>
    MeasurementVectorTraits::GetLength
    </Old>
    <New></New>
  </MigrationFix-Manual>

  <MigrationFix-Manual >
    <Old>
    MeasurementVectorTraits::SetLength
    </Old>
    <New></New>
  </MigrationFix-Manual>


</Change>

=== picslITK/ITK4_topics/Documentation/Migration/SymbolMacroHeader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">

<!--**
**
** SymbolMacroHeader.xml
**
** Please, make sure this file validates the following w3c test before committing it: http://validator.w3.org
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Symbol Macro Header Location
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Matthew McCormick
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-10-12
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      The definition for shared library symbol export macros was
      previously only definied in itkWin32Header.h for DLL creation. However, support was
      added to GCC visibility, so the ITK_EXPORT macro definition was moved to itkMacro.h.
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        #include "itkWin32Header.h"

        class ITK_EXPORT Gene
        {
        ]]>
      </Old>

      <New>
        <![CDATA[
        #include "itkMacro.h"

        class ITK_EXPORT Gene
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Id189a5a13d519a1399e5ff4ba5fe68d4afad3146
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Modules/Core/Common/include/itkMacro.h
      Modules/Core/Common/include/itkWin32Header.h
    </FileList>

    <!--**-->
    <!--** If the migration can be accomplished by a simple string-->
    <!--** substitution, then use the following construct to define-->
    <!--** the substitution rule.-->
    <!--**-->
     <MigrationFix-Automatic>
       <Old>
         <![CDATA[#include "itkWin32Header.h"]]>
       </Old>
       <New>
         <![CDATA[#include "itkMacro.h"]]>
       </New>
     </MigrationFix-Automatic>


    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/OrientationAdapterBaseRename.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** OrientationAdapterBaseRename.xml
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Orientation Adapter Base Rename
    </Title>

    <!--**
    ** Plain text description of the change
    **-->
    <Description>
      In order to match ITK style conventions, the filename
      should match the primary class name inside the file.
      This file was named differently than the class
      defined inside.
    </Description>

    <!--**
    ** Sample code snippets
    **-->
    <SampleCode>
      <Old>
        #include "itkOrientationAdapter.h"
      </Old>
      <New>
        #include "itkOrientationAdapterBase.h"
      </New>
    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Ib1bfac893da630656bede6262d5415c253a51ac3
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/Common/itkOrientationAdapter.h
      Code/Common/itkOrientationAdapterBase.h
      Code/Common/itkQuaternionOrientationAdapter.h
      Code/Common/itkSpatialOrientationAdapter.h
    </FileList>


<MigrationFix-Automatic>
  <Old>
  "itkOrientationAdapter.h"
  </Old>
  <New>
  "itkOrientationAdapterBase.h"
  </New>
</MigrationFix-Automatic>

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/DistanceMapDefaultBehavior.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">

<!--**
**
** MaurerDefaultBehavior.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
** Please, make sure this file validates the following w3c test before committing it: http://validator.w3.org
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Signed Distance Map Default Behavior
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      GaÃ«tan Lehmann
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-09-16
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      <![CDATA[
      BUG: Distance filter should use consistent defaults

      Distance maps are commonly regarded as know to be a way to
      compute exact Euclidean distance, but with the default values, that
      was not the case, forcing the user to change those values each time to
      get exact results.

      In order to make the all distance maps
      behave consistently, they should default to
      the natural Euclidean distance measures in physical space.

      The filters are configurable to run faster but with results that
      require end-user care to ensure that they are used properly (i.e.
      distances can be squares of either physical or voxel distances).

      ]]>
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        /* For Dannielsson, SignedDannielsson, SignedMaurer, DirectedHausdorff, and Hausdorff */

       DistanceFilterType::PointerPointer distanceFilter = DistanceFilterType::PointerType::New();
       distanceFilter->SetInput( reader->GetOutput() );
       /*ITKv3 default to fastest computation, but data dependant interpretations*/
       /*ITKv3 method defaulted to implied behavior of SetSquaredDistance(true), SetUseImageSpacing(false) */
       distanceFilter->Update();
        ]]>
      </Old>

      <New>
        <![CDATA[
       DistanceFilterType::PointerPointer distanceFilter = DistanceFilterType::PointerType::New();
       distanceFilter->SetInput( reader->GetOutput() );
       /*ITKv4 defaults to consistent physical space interpretation*/
       /*ITKv4 method defaults to SetSquaredDistance(false), SetUseImageSpacing(true) */
       distanceFilter->SetUseImageSpacing(false);/*Force ITKv3 default behavoir*/
       /* For SignedMaurer, the ITKv3 method used SetSquaredDistance(true), all others used (false)
       distanceFilter->SetSquaredDistance(true); /*Force ITKv3 default behavior*/
       distanceFilter->Update();
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Id688aaabc72041c866f285784f55db10769d0a55
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.h
      Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
      Modules/Nonunit/Review/include/itkMultiphaseDenseFiniteDifferenceImageFilter.hxx
    </FileList>
</Change>

=== picslITK/ITK4_topics/Documentation/Migration/FixedConvolutionImageFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">

<!--**
**
** FixedConvolutionImageFilter.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
** Please, make sure this file validates the following w3c test before committing it: http://validator.w3.org
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Fixed ConvolutionImageFilter
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Cory Quammen
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-09-27
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      <![CDATA[
      In convolution, the kernel is effectively flipped and swept across an
      image, and at each pixel the dot product between the kernel centered
      at the pixel and the image to convolve is computed and
      stored. Previously, the ConvolutionImageFilter was not performing the
      flip, and the existing tests were incorrect. This patch makes the
      ConvolutionImageFilter produce the correct output according to the
      predominant definition of the convolution operation, and the tests and
      test data have been modified accordingly.

      In addition, the method SetImageKernelInput() has been renamed to
      SetKernelImage() to be consistent with other filters such as
      MaskImageFilter and the registration classes.

      ]]>
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        typedef itk::ConvolutionImage< ImageType > ConvolutionFilterType;
        ConvolutionFilterType::Pointer convolutionFilter = ConvolutionFilterType::New();
        convolutionFilter->SetInput( inputImage );
        convolutionFilter->SetImageKernelInput( kernelImage );
        convolutionFilter->Update();
        ]]>
      </Old>

      <New>
        <![CDATA[
        #include <itkFlipImageFilter.h>

        // If you're existing code produced desired results, then you will need
        // to flip the kernel prior to setting it as the kernel image in the
        // convolution filter (assuming the kernel is not symmetric about each axis).
        typedef FlipImageFilter< TImage > FlipperType;
        typename FlipperType::Pointer flipper = FlipperType::New();
        typename FlipperType::FlipAxesArrayType axesArray;
        axesArray.Fill( true );
        flipper->SetFlipAxes( axesArray );
        flipper->SetInput( kernelImage );

        typedef itk::ConvolutionImage< ImageType > ConvolutionFilterType;
        ConvolutionFilterType::Pointer convolutionFilter = ConvolutionFilterType::New();
        convolutionFilter->SetInput( inputImage );
        convolutionFilter->SetKernelImage( kernelImage );
        convolutionFilter->Update();
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I689d3e4a627b2017f52d9b74998a1befae1e9fe7
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Modules/Filtering/Convolution/include/itkConvolutionImageFilter.hxx
      Modules/Filtering/Convolution/test/Baseline/itkConvolutionImageFilterTestSobelX.nrrd.md5
      Modules/Filtering/Convolution/test/Baseline/itkConvolutionImageFilterTestSobelY.nrrd.md5
      Modules/Filtering/Convolution/test/CMakeLists.txt
      Modules/Filtering/Convolution/test/itkConvolutionImageFilterDeltaFunctionTest.cxx
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     <![CDATA[MipsleledName]]>
    **   </Old>
    **   <New>
    **     <![CDATA[MisspelledName]]>
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>
