=== picslITK/ITK4_topics/Documentation/Migration/ITKMigration.dtd
<!ELEMENT Change ( Title, Author*, Date*, Description, SampleCode*, Gerrit-ChangeId, FileList, MigrationFix-Automatic*, MigrationFix-Manual* ) >

<!ELEMENT Description ( #PCDATA ) >

<!ELEMENT FileList ( #PCDATA ) >

<!ELEMENT Gerrit-ChangeId ( #PCDATA ) >

<!ELEMENT MigrationFix-Automatic ( Old, New ) >

<!ELEMENT MigrationFix-Manual ( Old, New ) >

<!ELEMENT New ( #PCDATA ) >

<!ELEMENT Old ( #PCDATA ) >

<!ELEMENT SampleCode ( Old*, New* ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Author ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

=== picslITK/ITK4_topics/Documentation/Migration/RemoveAliasITK_TYPENAME.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** RemoveAliasITK_TYPENAME.xml
**
**-->
<Change>
  <!--**
      ** ITK_TYPENAME removed
      **-->
  <Title>
    ITK_TYPENAME deprecated to ITKV3_COMPATIBILITY
  </Title>

  <Author>
    Hans Johnson
  </Author>

  <!--**
      ** Plain text description of the change
      **-->
  <Description>
    <![CDATA[
    ITK_TYPENAME has been removed. Early in the development of
    ITK, some compilers did not support typename.
    ITK provided an empty #define to hide this deficiency.
    Modern C++98 compilers implement typename
    correctly and the work-around is no longer needed.
    ]]>
  </Description>

  <!--**
      ** Sample code snippets
      **-->
  <SampleCode>
    <Old>
      ITK_TYPENAME
    </Old>
    <New>
      typename
    </New>

  </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
    If00a940f027036e4a03f760ccd1b465504fe1fa0
    I72882c7b35161935c087efa1b33122a958bfa7e4
    </Gerrit-ChangeId>

  <!--**
      ** List of all changed files from the topic branch
      **-->
  <FileList>
    Code/Common/itkMacro.h
    Documentation/Migration/RenamedFunctionsToFunctors.xml
    Modules/Core/Common/include/itkBinaryThresholdSpatialFunction.h
    Modules/Core/Common/include/itkCellInterface.h
    Modules/Core/Common/include/itkConstNeighborhoodIterator.h
    Modules/Core/Common/include/itkFloodFilledFunctionConditionalConstIterator.h
    Modules/Core/Common/include/itkFloodFilledFunctionConditionalConstIterator.hxx
    Modules/Core/Common/include/itkNeighborhoodInnerProduct.h
    Modules/Core/Common/include/itkShapedFloodFilledFunctionConditionalConstIterator.h
    Modules/Core/Common/include/itkShapedFloodFilledFunctionConditionalConstIterator.hxx
    Modules/Core/Common/include/itkWin32Header.h
    Modules/Core/ImageFunction/include/itkBSplineResampleImageFunction.h
    Modules/Core/ImageFunction/include/itkCovarianceImageFunction.h
    Modules/Core/ImageFunction/include/itkExtrapolateImageFunction.h
    Modules/Core/ImageFunction/include/itkInterpolateImageFunction.h
    Modules/Core/ImageFunction/include/itkMeanImageFunction.h
    Modules/Core/ImageFunction/include/itkMedianImageFunction.h
    Modules/Core/ImageFunction/include/itkScatterMatrixImageFunction.h
    Modules/Core/ImageFunction/include/itkSumOfSquaresImageFunction.h
    Modules/Core/ImageFunction/include/itkVarianceImageFunction.h
    Modules/Core/ImageFunction/include/itkVectorInterpolateImageFunction.h
    Modules/Core/ImageFunction/include/itkVectorMeanImageFunction.h
    Modules/Core/SpatialObjects/include/itkBoxSpatialObject.hxx
    Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
    Modules/Filtering/ImageCompose/include/itkJoinImageFilter.h
    Modules/Filtering/ImageFeature/include/itkHessianRecursiveGaussianImageFilter.h
    Modules/Filtering/ImageFilterBase/include/itkMaskNeighborhoodOperatorImageFilter.h
    Modules/Filtering/ImageFilterBase/include/itkNeighborhoodOperatorImageFilter.h
    Modules/Filtering/ImageFilterBase/include/itkNullImageToImageFilterDriver.hxx
    Modules/Filtering/ImageGradient/include/itkGradientMagnitudeRecursiveGaussianImageFilter.h
    Modules/Filtering/ImageGradient/include/itkGradientRecursiveGaussianImageFilter.h
    Modules/Filtering/ImageGrid/include/itkBSplineDownsampleImageFilter.h
    Modules/Filtering/ImageGrid/include/itkInterpolateImagePointsFilter.h
    Modules/Filtering/ImageGrid/include/itkSliceBySliceImageFilter.h
    Modules/Filtering/ImageIntensity/include/itkAdaptImageFilter.h
    Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.h
    Modules/Filtering/ImageIntensity/include/itkNormalizeImageFilter.hxx
    Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx
    Modules/Filtering/ImageStatistics/include/itkMeanProjectionImageFilter.h
    Modules/Filtering/ImageStatistics/include/itkNormalizedCorrelationImageFilter.h
    Modules/Filtering/ImageStatistics/include/itkNormalizedCorrelationImageFilter.hxx
    Modules/Filtering/ImageStatistics/include/itkStandardDeviationProjectionImageFilter.h
    Modules/Filtering/LabelMap/include/itkLabelImageToShapeLabelMapFilter.h
    Modules/Filtering/LabelMap/include/itkLabelImageToStatisticsLabelMapFilter.h
    Modules/Filtering/LabelMap/include/itkObjectByObjectLabelMapFilter.h
    Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkAnchorCloseImageFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkAnchorOpenImageFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkGrayscaleConnectedClosingImageFilter.hxx
    Modules/Filtering/MathematicalMorphology/include/itkGrayscaleConnectedOpeningImageFilter.hxx
    Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.hxx
    Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.hxx
    Modules/Filtering/MathematicalMorphology/include/itkMovingHistogramMorphologicalGradientImageFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkReconstructionByDilationImageFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkReconstructionByErosionImageFilter.h
    Modules/Filtering/MathematicalMorphology/include/itkSharedMorphologyUtilities.hxx
    Modules/Filtering/MathematicalMorphology/include/itkVanHerkGilWermanUtilities.hxx
    Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshDecimationCriteria.h
    Modules/IO/Base/include/itkImageFileReader.h
    Modules/IO/Base/include/itkImageFileReader.hxx
    Modules/IO/Mesh/include/itkMeshFileReader.h
    Modules/IO/Mesh/include/itkMeshFileReader.hxx
    Modules/Nonunit/Deprecated/include/itkCompose2DCovariantVectorImageFilter.h
    Modules/Nonunit/Deprecated/include/itkCompose2DVectorImageFilter.h
    Modules/Nonunit/Deprecated/include/itkCompose3DCovariantVectorImageFilter.h
    Modules/Nonunit/Deprecated/include/itkCompose3DVectorImageFilter.h
    Modules/Nonunit/Deprecated/include/itkComposeRGBImageFilter.h
    Modules/Nonunit/Deprecated/include/itkImageToVectorImageFilter.h
    Modules/Nonunit/Review/include/itkAreaClosingImageFilter.h
    Modules/Nonunit/Review/include/itkAreaOpeningImageFilter.h
    Modules/Nonunit/Review/include/itkBoxUtilities.h
    Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
    Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.hxx
    Modules/Nonunit/Review/include/itkMaskedRankImageFilter.h
    Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
    Modules/Nonunit/Review/include/itkRankImageFilter.h
    Modules/Nonunit/Review/include/itkScalarChanAndVeseDenseLevelSetImageFilter.h
    Modules/Nonunit/Review/include/itkScalarChanAndVeseSparseLevelSetImageFilter.h
    Modules/Nonunit/Review/include/itkValuedRegionalMaximaImageFilter.h
    Modules/Nonunit/Review/include/itkValuedRegionalMinimaImageFilter.h
    Modules/Nonunit/Review/test/itkImageFunctionTest.cxx
    Modules/Numerics/NarrowBand/include/itkNarrowBand.hxx
    Modules/Numerics/Statistics/include/itkScalarImageToRunLengthFeaturesFilter.hxx
    Modules/Numerics/Statistics/include/itkScalarImageToTextureFeaturesFilter.hxx
    Modules/Registration/Common/include/itkHistogramImageToImageMetric.hxx
    Modules/Registration/Common/include/itkKappaStatisticImageToImageMetric.hxx
    Modules/Registration/Common/include/itkMatchCardinalityImageToImageMetric.h
    Modules/Registration/Common/include/itkMeanReciprocalSquareDifferencePointSetToImageMetric.hxx
    Modules/Registration/Common/include/itkMeanSquaresPointSetToImageMetric.hxx
    Modules/Registration/Common/include/itkNormalizedCorrelationImageToImageMetric.hxx
    Modules/Registration/Common/include/itkNormalizedCorrelationPointSetToImageMetric.hxx
    Modules/Segmentation/Classifiers/include/itkBayesianClassifierInitializationImageFilter.hxx
    Modules/Segmentation/ConnectedComponents/include/itkVectorConnectedComponentImageFilter.h
    Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
    Modules/Segmentation/LevelSets/include/itkSegmentationLevelSetFunction.h
    Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx
    Modules/Segmentation/LevelSets/include/itkVectorThresholdSegmentationLevelSetFunction.h
    Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.hxx
    Modules/Segmentation/Watersheds/include/itkIsolatedWatershedImageFilter.hxx
    Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
  </FileList>

<MigrationFix-Automatic>
  <Old>
    ITK_TYPENAME
  </Old>
  <New>
    typename
  </New>
</MigrationFix-Automatic>
</Change>

=== picslITK/ITK4_topics/Documentation/Migration/CArrayRemoval.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** CArrayRemoval.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      C Array Removal
    </Title>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      C arrays are not used any more as method parameter or return value.

      There are several places in ITK where C arrays are used as method
      parameter or return value instead of stronger array like types, like
      itk::Index, itk::Size, itk::Offset, itk::FixedArray or itk::Array.
      Using stronger types makes more efficient the error checking at compile
      time and enhance the user integration by using the same types and
      conventions than elsewhere.

      More important, the C arrays are not wrappable without further
      information that we don&apos;t have at wrap time. As a consequence, the
      classes which are using them are at best partially usable in Python,
      Java or Tcl. Using stronger types completely fix that problem.

      Backward compatibility is fully preserved for input parameters, but
      not for return values. Usually, return values will require an additional
      call to GetDataPointer(), m_Offset, m_Size or m_Index to be fully compatible.

      However, to pass and get the values to or from the filter it is adviced to rather
      use the stronger type (itk::Index, itk::Size, itk::Offset, itk::FixedArray or
      itk::Array) used to replace the C array instead of the legacy C array.
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        const long * outputOffset = filter-&gt;GetOutputOffset();
        const long * outputIndex = filter-&gt;GetOutputIndex();
        const unsigned long * outputSize = filter-&gt;GetOutputSize();
        const float * outweights =  filter-&gt;GetWeights();
        const double * spacingValue = import-&gt;GetSpacing();
        const double * originValue = import-&gt;GetOrigin();
      </Old>

      <New>
        const long * outputOffset = filter-&gt;GetOutputOffset().m_Offset;
        const long * outputIndex = filter-&gt;GetOutputIndex().m_Index;
        const unsigned long * outputSize = filter-&gt;GetOutputSize().m_Size;
        const float * outweights =  filter-&gt;GetWeights().GetDataPointer();
        const double * spacingValue = import-&gt;GetSpacing().GetDataPointer();
        const double * originValue = import-&gt;GetOrigin().GetDataPointer();
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Id1f1993ab89fac86dfcd3225dd30e352f01a433e
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/Algorithms/itkFastChamferDistanceImageFilter.h
      Code/Algorithms/itkMultiResolutionPDEDeformableRegistration.h
      Code/Algorithms/itkMultiResolutionPDEDeformableRegistration.txx
      Code/Algorithms/itkPDEDeformableRegistrationFilter.h
      Code/BasicFilters/itkBilateralImageFilter.txx
      Code/BasicFilters/itkChangeInformationImageFilter.h
      Code/BasicFilters/itkChangeInformationImageFilter.txx
      Code/BasicFilters/itkDisplacementFieldJacobianDeterminantFilter.h
      Code/BasicFilters/itkDisplacementFieldJacobianDeterminantFilter.txx
      Code/BasicFilters/itkExpandImageFilter.h
      Code/BasicFilters/itkExpandImageFilter.txx
      Code/BasicFilters/itkGaussianImageSource.h
      Code/BasicFilters/itkGaussianImageSource.txx
      Code/BasicFilters/itkGradientImageToBloxBoundaryPointImageFilter.h
      Code/BasicFilters/itkGradientImageToBloxBoundaryPointImageFilter.txx
      Code/BasicFilters/itkGrayscaleMorphologicalClosingImageFilter.txx
      Code/BasicFilters/itkGrayscaleMorphologicalOpeningImageFilter.txx
      Code/BasicFilters/itkImportImageFilter.h
      Code/BasicFilters/itkImportImageFilter.txx
      Code/BasicFilters/itkPadImageFilter.h
      Code/BasicFilters/itkReconstructionImageFilter.txx
      Code/BasicFilters/itkShrinkImageFilter.h
      Code/BasicFilters/itkShrinkImageFilter.txx
      Code/BasicFilters/itkVectorExpandImageFilter.h
      Code/BasicFilters/itkVectorExpandImageFilter.txx
      Code/BasicFilters/itkVectorGradientMagnitudeImageFilter.h
      Code/BasicFilters/itkVectorGradientMagnitudeImageFilter.txx
      Code/IO/itkStimulateImageIO.h
      Code/Review/itkBinaryMorphologicalClosingImageFilter.txx
      Code/Review/itkWarpHarmonicEnergyCalculator.h
      Code/Review/itkWarpHarmonicEnergyCalculator.txx
      Examples/Registration/DeformableRegistration16.cxx
      Migration/CArrayRemoval.xml
      Testing/Code/Algorithms/itkFastChamferDistanceImageFilterTest.cxx
      Testing/Code/BasicFilters/itkChangeInformationImageFilterTest.cxx
      Testing/Code/BasicFilters/itkImportImageTest.cxx
    </FileList>

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/OStringStreamRemoved.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** OStringStreamRemoval.xml
**
**-->
<Change>
  <!--**
      ** OStringStream removed
      **-->
  <Title>
    OStringStream removed.
  </Title>

  <Author>
    Bradley Lowekamp
  </Author>

  <!--**
      ** Plain text description of the change
      **-->
  <Description>
    <![CDATA[
    itk::OStringStream has been removed. Early in the development of
    ITK, some compilers did not support std::stringstream. ITK
    provided a wrapper to hide differences between std::stringstream
    and the old ostrstream (which has been deprecated by the C++
    standard). Modern C++98 compilers implement std::ostringstream
    correctly and a wrapper is no longer needed.
    ]]>
  </Description>

  <!--**
      ** Sample code snippets
      **-->
  <SampleCode>
    <Old>
      itk::OStringStream msg;
    </Old>
    <New>
      std::ostringstream msg;
    </New>
  </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
    </Gerrit-ChangeId>

  <!--**
      ** List of all changed files from the topic branch
      **-->
  <FileList>
    Code/Common/itkMacro.h
    Code/Algorithms/itkFEMRegistrationFilter.txx
    Code/Algorithms/itkMRFImageFilter.txx
    Code/BasicFilters/itkCannyEdgeDetectionImageFilter.txx
    Code/Common/itkChainCodePath2D.cxx
    Code/Common/itkConstNeighborhoodIterator.h
    Code/Common/itkExceptionObject.cxx
    Code/Common/itkImageSource.txx
    Code/Common/itkLoggerBase.cxx
    Code/Common/itkTestMain.h
    Code/Common/itkTransform.txx
    Code/Common/itkWin32OutputWindow.cxx
    Code/IO/itkGDCMImageIO.cxx
    Code/IO/itkImageFileReader.txx
    Code/IO/itkImageFileWriter.txx
    Code/IO/itkTestDriver.cxx
    Code/IO/itkTransformFileReader.cxx
    Code/Numerics/FEM/itkFEMException.cxx
    Code/Numerics/FEM/itkFEMItpackSparseMatrix.cxx
    Code/Numerics/FEM/itkFEMLinearSystemWrapper.cxx
    Code/Numerics/FEM/itkFEMLinearSystemWrapperItpack.cxx
    Code/Numerics/itkAmoebaOptimizer.h
    Code/Numerics/itkCumulativeGaussianOptimizer.h
    Code/Numerics/itkExhaustiveOptimizer.h
    Code/Numerics/itkGradientDescentOptimizer.h
    Code/Numerics/itkLBFGSBOptimizer.h
    Code/Numerics/itkLBFGSOptimizer.h
    Code/Numerics/itkLevenbergMarquardtOptimizer.cxx
    Code/Numerics/itkOnePlusOneEvolutionaryOptimizer.h
    Code/Numerics/itkOptimizer.cxx
    Code/Numerics/itkPowellOptimizer.h
    Code/Numerics/itkRegularStepGradientDescentBaseOptimizer.h
    Code/Numerics/itkSPSAOptimizer.cxx
    Code/Review/itkAnchorErodeDilateImageFilter.txx
    Code/Review/itkAnchorOpenCloseImageFilter.txx
    Code/Review/itkBoxImageFilter.txx
    Code/Review/itkBruker2DSEQImageIO.cxx
    Code/Review/itkPhilipsPAR.cxx
    Code/Review/itkPhilipsRECImageIO.cxx
    Code/Review/itkQuadEdge.h
    Code/Review/itkTransformIOBase.cxx
    Code/Review/itkTxtTransformIO.cxx
    Code/Review/itkVanHerkGilWermanErodeDilateImageFilter.txx
    Code/SpatialObject/itkSpatialObject.txx
    Testing/Code/BasicFilters/itkTwoOutputExampleImageFilterTest.cxx
    Testing/Code/IO/itkImageFileWriterStreamingPastingCompressingTest1.cxx
  </FileList>

<MigrationFix-Automatic>
  <Old>
    itk::OStringStream
  </Old>
  <New>
    std::ostringstream
  </New>
</MigrationFix-Automatic>
</Change>

=== picslITK/ITK4_topics/Documentation/Migration/MetaArrowFixMemoryLeaksAndConvertToITKObject.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** MetaArrowFixMemoryLeaksAndConvertToITKObject.xml
**
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Meta Arrow Fix Memory Leaks
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Luis Ibanez
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2010-12-23
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      <![CDATA[
      A review of the MetaArrowConverter code revealed that this class does not
      use any state information (does not have any member variables) and therefore
      all of its methods can be declared static. The arguments of many of the methods
      were also missing to use a 'const' declaration, despite the fact that the execution
      of the function did not modified the content of the argument.

      The main API change here is that now MetaArrowConverter is an ITK object and
      it has to be constructed with the typical SmartPointer notation of

          MetaArrowConverterType::Pointer converter = MetaArrowConverterType::New();

      while before it could be constructed as:

          MetaArrowConverterType  converter;

      The default constructor has now been declared 'protected' so the second
      notation will result in compilation errors.

      BUG: MetaArrow memory leaks.
      MetaArrowConverter is now  an ITK Object and uses smart pointers.
      Several delete were added to places where irresponsible calls to new
      MetaArrow were done without regards for cleaning up the allocations.

      ENH: Fixing const in ArrowSpatialObject::GetLength.

      ENH: Making most methods of itkMetaArrowConverter to be static,
      since this class doesn&apos;t really have a state (no member variables).
      As pointed out by Brad Lowekamp during Gerrit review.
      ]]>
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        typedef MetaArrowConverter<Dimension> MetaArrowConverterType;
        MetaArrowConverterType  converter;
        ]]>
      </Old>

      <New>
        <![CDATA[
         typedef MetaArrowConverter<Dimension> MetaArrowConverterType;
         MetaArrowConverterType::Pointer converter = MetaArrowConverterType::New();

         SpatialObjectPointer spatialObject = converter->ReadMeta( inputFilename );
         converter->WriterMeta( spatialObject, outputFilename );

         MetaArrow * arrow = GetArrowSomeHow();
         SpatialObjectPointer arrowObject = converter->MetaArrowToArrowSpatialObject( arrow );

         MetaArrow * anotherArrow = converter->ArrowSpatialObjectToMetaArrow( arrowObject );

         //
         // Or with the static notation:
         //
         SpatialObjectPointer spatialObject = MetaArrowConverterType::ReadMeta( inputFilename );
         MetaArrowConverterType::WriterMeta( spatialObject, outputFilename );

         MetaArrow * arrow = GetArrowSomeHow();
         SpatialObjectPointer arrowObject = MetaArrowConverterType::MetaArrowToArrowSpatialObject( arrow );

         MetaArrow * anotherArrow = MetaArrowConverterType::ArrowSpatialObjectToMetaArrow( arrowObject );
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I6c4eafc97cf2c3859d9a624985494ebe680d6044
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/SpatialObject/itkArrowSpatialObject.h
      Code/SpatialObject/itkMetaArrowConverter.h
      Code/SpatialObject/itkMetaArrowConverter.txx
      Code/SpatialObject/itkMetaSceneConverter.txx
      Testing/Code/SpatialObject/itkMetaArrowConverterTest.cxx
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   Invocations to default constructor must be replaced
    **   with the typical notation of SmartPointers.
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/BRAINS2MaskImageIORemoved.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** BRAINS2MaskImageIORemoval.xml
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      The BRAINS2MaskImageIO class is removed.
    </Title>

    <!--**
    ** Plain text description of the change
    **-->
    <Description>
      The Brains2Mask file format has very limited functionality
      outside the legacy brains2 program.  This file format
      does not have sufficient information for supporting
      orientation of masks, and even the Iowa contributors
      have given up on using the ITK Brains2Mask as a file
      format from ITK.  This is a legacy format that was
      never included in the default file reader lists.
    </Description>

    <!--**
    ** Sample code snippets
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        #include "itkBrains2MaskImageIO.h"
        include "itkBrains2MaskImageIOFactory.h"
        itk::ObjectFactoryBase::RegisterFactory(itk::Brains2MaskImageIOFactory::New() );
        ]]>
      </Old>
      <New>
        // Don't include headers or register factory
      </New>
    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      d8f950b66829c531aedef5680c35c88d1edbf5b7
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/IO/CMakeLists.txt
      Code/IO/itkBrains2HeaderBase.cxx
      Code/IO/itkBrains2HeaderBase.h
      Code/IO/itkBrains2HeaderFactory.cxx
      Code/IO/itkBrains2HeaderFactory.h
      Code/IO/itkBrains2IPLHeaderInfo.cxx
      Code/IO/itkBrains2IPLHeaderInfo.h
      Code/IO/itkBrains2MaskHeaderInfo.cxx
      Code/IO/itkBrains2MaskHeaderInfo.h
      Code/IO/itkBrains2MaskImageIO.cxx
      Code/IO/itkBrains2MaskImageIO.h
      Code/IO/itkBrains2MaskImageIOFactory.cxx
      Code/IO/itkBrains2MaskImageIOFactory.h
      Testing/Code/IO/CMakeLists.txt
      Testing/Code/IO/itkBrains2MaskImageIOTest.cxx
      Testing/Code/IO/itkIOHeaderTest.cxx
    </FileList>

<MigrationFix-Manual>
  <Old>
    <![CDATA[
    #include "itkBrains2MaskImageIO.h"
    #include "itkBrains2MaskImageIOFactory.h"
    itk::ObjectFactoryBase::RegisterFactory(itk::Brains2MaskImageIOFactory::New() );
    ]]>
  </Old>
  <New>
    <![CDATA[
    Remove #include statemets for BRAINS2Mask classes.
    Remove c++ statement that registered the BRAINS2Mask factory.
    In the unlikely event you need to convert BRAINS2 masks, there is a program included in
    the BRAINS3 project on nitrc.org, called ConvertMaskToBinaryImage, that can be used to do this.
    See http://www.
    ]]>
  </New>
</MigrationFix-Manual>

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/RemoveditkSemaphore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** RemoveditkSemaphore.xml
**
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Removed itkSemaphore
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Bradley Lowekamp
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-02-19
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      itk::Semaphore has been removed and placed in the deprecated module.

      The implementation contained a mixture of thread semaphores and
      inter-process semaphores. This gives vastly different
      performance characteristics across platforms.

      While you can simple continue using the old class, it is
      strongly recommended to update to use mutexes and conditional
      variables. By doing so you have the potential to take advantage
      of ITKv4 improved threading model.

      ENH: removes semaphore in favor of mutex and conditional
      This was the only class in ITK which utilized a semaphore. This was
      replaced with the equivalent mutex and conditioanl variable.

    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        itk::Semaphore::Pointer m_Semaphore = itk::Semaphore::New();

        m_Semaphore->Up();

        m_Semaphore->Down()
      </Old>

      <New>
        <![CDATA[
        int m_Semaphore;
        SimpleMutexLock m_Lockl
        ConditionalVariable::Pointer m_Condition = ConditionalVariable::New();

        m_Lock.Lock();
        ++m_Semaphore;
        m_Condition->Signal();
        m_Lock.Unlock();

        m_Lock.Lock();
        if ( m_Semaphore == 0 )
        {
        m_Condition->Wait( & td.m_Lock);
        }
        --m_Semaphore;
        m_Lock.Unlock();
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I5afecd8f29b07beed97534731e677214d1cceb3b
      I175f87493476d473a38f20f837479a7fe882230a
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Code/Common/CMakeLists.txt
      Code/Common/itkSemaphore.cxx
      Code/Common/itkSemaphore.h
      Code/Common/itkSemaphoreNoThreads.cxx
      Code/Common/itkSemaphorePThreads.cxx
      Code/Common/itkSemaphoreWinThreads.cxx
      Testing/Code/Common/CMakeLists.txt
      Testing/Code/Common/itkCommonHeaderTest.cxx
      Testing/Code/Common/itkSemaphoreTest.cxx
      Code/BasicFilters/itkParallelSparseFieldLevelSetImageFilter.h
      Code/BasicFilters/itkParallelSparseFieldLevelSetImageFilter.txx
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>
