=== picslITK/ITK4_topics/Documentation/Migration/ITKMigration.dtd
<!ELEMENT Change ( Title, Author*, Date*, Description, SampleCode*, Gerrit-ChangeId, FileList, MigrationFix-Automatic*, MigrationFix-Manual* ) >

<!ELEMENT Description ( #PCDATA ) >

<!ELEMENT FileList ( #PCDATA ) >

<!ELEMENT Gerrit-ChangeId ( #PCDATA ) >

<!ELEMENT MigrationFix-Automatic ( Old, New ) >

<!ELEMENT MigrationFix-Manual ( Old, New ) >

<!ELEMENT New ( #PCDATA ) >

<!ELEMENT Old ( #PCDATA ) >

<!ELEMENT SampleCode ( Old*, New* ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Author ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

=== picslITK/ITK4_topics/Documentation/Migration/RenamedGradientToMagnitudeImageFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** RenamedGradientToMagnitudeImageFilter.xml
**
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Renamed GradientToMagnitudeImageFilter to VectorMagnitudeImageFilter
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      David Doria
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-05-03
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      GradientToMagnitudeImageFilter has been renamed to VectorMagnitudeImageFilter.
      It has been moved from the ImageGradient module to the ImageIntensity module.
      GradientToMagnitudeImageFilter has been made a subclass of VectorMagnitudeImageFilter
      and moved to the Deprecated module.

      The majority of the changed files were tests which used GradientToMagnitudeImageFilter
      internally.

    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
      <![CDATA[
	#include "itkGradientToMagnitudeImageFilter.h"
	typedef itk::GradientToMagnitudeImageFilter<VectorImageType,FloatImageType> FilterType;
        FilterType::Pointer filter = FilterType::New();
      ]]>
      </Old>

      <New>
      <![CDATA[
	#include "itkVectorMagnitudeImageFilter.h"
	typedef itk::VectorMagnitudeImageFilter<VectorImageType,FloatImageType> FilterType;
        FilterType::Pointer filter = FilterType::New();
      ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I5afecd8f29b07beed97534731e677214d1cceb3b
      I175f87493476d473a38f20f837479a7fe882230a
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Documentation/Migration/RenamedGradientToMagnitudeImageFilter.xml
      Modules/Core/Common/test/itkNumericTraitsTest.cxx
      Modules/Filtering/ImageFeature/test/itkGradientVectorFlowImageFilterTest.cxx
      Modules/Filtering/ImageGradient/test/CMakeLists.txt
      Modules/Filtering/ImageGradient/test/itkDifferenceOfGaussiansGradientTest.cxx
      Modules/Filtering/ImageGradient/test/itkGradientToMagnitudeImageFilterTest.cxx
      Modules/Filtering/ImageGradient/test/itkImageGradientHeaderTest.cxx
      Modules/Filtering/ImageIntensity/include/itkVectorMagnitudeImageFilter.h
      Modules/Filtering/ImageGradient/include/itkGradientToMagnitudeImageFilter.h
      Modules/Filtering/ImageIntensity/test/CMakeLists.txt
      Modules/Filtering/ImageIntensity/test/itkVectorMagnitudeImageFilterTest.cxx
      Modules/Nonunit/Deprecated/include/itkGradientToMagnitudeImageFilter.h
      Modules/Filtering/ImageGradient/include/itkGradientToMagnitudeImageFilter.h
      Modules/Nonunit/Deprecated/test/CMakeLists.txt
      Modules/Nonunit/Deprecated/test/itkGradientToMagnitudeImageFilterTest.cxx
    </FileList>

    <MigrationFix-Automatic>
       <Old>
         GradientToMagnitudeImageFilter
       </Old>
       <New>
         VectorMagnitudeImageFilter
       </New>
    </MigrationFix-Automatic>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/LabelObjectImproveAttributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--***************************************************************************
**
** MoveGetSetLengthMeasurementVectorTraits.xml
**
** This is the second sample Migration Guide XML document. For full details,
** see MoveGetSetLengthMeasurementVectorTraits.xml. One aditional required
** element has been added which is <Title>. This will be used for the title of
** the migration guide page.
**
****************************************************************************-->

<Change>

  <!--
  ** Title for the published page
  **-->
  <Title>
  Improve Attribute Names for Labels
  </Title>

  <!--
  ** English language description of what was changed and why
  **-->
  <Description>
  <![CDATA[
  This change updates the attribute names for the LabelObject system.  The
  changes are:

  BinaryElongation        -> Elongation
  BinaryFlatness          -> Flatness
  BinaryPrincipalMoments  -> PrincipalMoments
  BinaryPrincipalAxes     -> PrincipalAxes
  Elongation              -> WeightedElongation
  EquivalentEllipsoidSize -> EquivalentEllipsoidDiameter
  EquivalentPerimeter     -> EquivalentSphericalPerimeter
  EquivalentRadius        -> EquivalentSphericalRadius
  Flatness                -> WeightedFlatness
  PhysicalSizeOnBorder    -> PerimeterOnBorder
  Region                  -> BoundingBox
  PrincipalAxes           -> WeightedPrincipalAxes
  PrincipalMoments        -> WeightedPrincipalMoments
  Sigma                   -> StandardDeviation
  Size                    -> NumberOfPixels
  SizeOnBorder            -> NumberOfPixelsOnBorder
  ]]>
  </Description>

  <!--
  ** Sample code to illustrate the fix process
  **-->
  <SampleCode>
    <Old>
    <![CDATA[
    typedef ShapeLabelObject LabelObjectType;
    LabelObjectType::Pointer labelObject;
    LabelObjectType::RegionType region = labelObject->GetRegion();
    ]]>
    </Old>

    <New>
    <![CDATA[
    typedef TLabelObject LabelObjectType;
    LabelObjectType::Pointer labelObject;
    LabelObjectType::RegionType region = labelObject->GetBoundingBox();
    ]]>
    </New>
  </SampleCode>


  <!--
  ** The asociated Gerrit entry for this API change
  **-->
  <Gerrit-ChangeId>
  Ib5bdca1cd1809490f1c5a0f991c7cc2714d33c70
  </Gerrit-ChangeId>

  <!--
  ** List of all files that were changed (might be automatically populated by
  ** git hook?)
  **-->
  <FileList>
  Code/Review/itkBinaryFillholeImageFilter.txx
  Code/Review/itkBinaryGrindPeakImageFilter.txx
  Code/Review/itkBinaryShapeKeepNObjectsImageFilter.txx
  Code/Review/itkBinaryShapeOpeningImageFilter.txx
  Code/Review/itkLabelMapUtilities.h
  Code/Review/itkLabelShapeKeepNObjectsImageFilter.txx
  Code/Review/itkLabelShapeOpeningImageFilter.txx
  Code/Review/itkShapeKeepNObjectsLabelMapFilter.txx
  Code/Review/itkShapeLabelMapFilter.txx
  Code/Review/itkShapeLabelObject.h
  Code/Review/itkShapeLabelObjectAccessors.h
  Code/Review/itkShapeOpeningLabelMapFilter.txx
  Code/Review/itkShapeRelabelImageFilter.txx
  Code/Review/itkShapeRelabelLabelMapFilter.txx
  Code/Review/itkShapeUniqueLabelMapFilter.txx
  Code/Review/itkStatisticsLabelMapFilter.txx
  Code/Review/itkStatisticsLabelObject.h
  Code/Review/itkStatisticsLabelObjectAccessors.h
  Testing/Code/Review/itkAttributePositionLabelMapFilterTest1.cxx
  Testing/Code/Review/itkAttributeUniqueLabelMapFilterTest1.cxx
  Testing/Code/Review/itkLabelMapToAttributeImageFilterTest1.cxx
  Testing/Code/Review/itkShapeLabelObjectAccessorsTest1.cxx
  </FileList>



  <!--
  ** Migration guide rules............ Still need to figure out how this will
  **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/RemoveInvertBinaryIntensityFunctor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">

<!--**
**
** RemoveInvertBinaryIntensityFunctor.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
** Please, make sure this file validates the following w3c test before committing it: http://validator.w3.org
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Remove Invert Binary Intensity Functor
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      Arnaud Gelas
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-06-28
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      <![CDATA[
      Remove itk::Functor::InvertBinaryIntensityFunctor which was not used
      in the whole toolkit, and not visible for users (it did not show up in
      the doxygen documentation).

      ]]>
    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        <![CDATA[
        ]]>
      </Old>

      <New>
        <![CDATA[
        ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Ia0afc3aef203c3f1c5742553dba450d614b1c3da
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Documentation/Migration/RemoveInvertBinaryIntensityFunctor.xml
      Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.h
      Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.txx
      Modules/Filtering/DistanceMap/itk-module.cmake
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/RemoveConstantOperationFilters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** RemoveConstantOperationFilters.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      Remove Constant Operation Filters
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      GaÃ«tan Lehmann
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-03-29
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      BinaryFunctorImageFilter as been modified to take a constant as one of the inputs.
      That way the users have directly access to all the transforms based
      on BinaryFunctorImageFilter with a constant on one of the operand.
      This removes the need for AddConstantToImageFilter, DivideByConstantImageFilter,
      MultiplyByConstantImageFilter and SubtractConstantFromImageFilter and add
      the ability to set one or the other operand.

    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
      <![CDATA[
      #include "itkMultiplyByConstantImageFilter.h"
      typedef MultiplyByConstantImageFilter<
        DeformationFieldType,
        TimeStepType, DeformationFieldType >                MultiplyType;
      ]]>
      </Old>

      <New>
      <![CDATA[
      #include "itkMultiplyImageFilter.h"
      typedef MultiplyImageFilter< DeformationFieldType,
        itk::Image<TimeStepType, ImageDimension>,
        DeformationFieldType >                              MultiplyType;
      ]]>
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      I328d66b64485bbafe04a47e95674d98a9d3bdace
      Ia4b95dbb9dd82f176246e6b84870cf1dfdd217fa
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.txx
      Modules/Filtering/ImageFilterBase/include/itkBinaryFunctorImageFilter.h
      Modules/Filtering/ImageFilterBase/include/itkBinaryFunctorImageFilter.txx
      Modules/Filtering/ImageIntensity/include/itkDivideImageFilter.h
      Modules/Nonunit/Review/include/itkAddConstantToImageFilter.h
      Modules/Nonunit/Review/include/itkDiffeomorphicDemonsRegistrationFilter.h
      Modules/Nonunit/Review/include/itkDiffeomorphicDemonsRegistrationFilter.txx
      Modules/Nonunit/Review/include/itkDivideByConstantImageFilter.h
      Modules/Nonunit/Review/include/itkExponentialDeformationFieldImageFilter.h
      Modules/Nonunit/Review/include/itkExponentialDeformationFieldImageFilter.txx
      Modules/Nonunit/Review/include/itkFastSymmetricForcesDemonsRegistrationFilter.h
      Modules/Nonunit/Review/include/itkFastSymmetricForcesDemonsRegistrationFilter.txx
      Modules/Nonunit/Review/include/itkMultiplyByConstantImageFilter.h
      Modules/Nonunit/Review/include/itkSubtractConstantFromImageFilter.h
      Modules/Nonunit/Review/test/itkAddConstantToImageFilterTest.cxx
      Modules/Nonunit/Review/test/itkDiscreteGaussianDerivativeImageFilterScaleSpaceTest.cxx
      Modules/Nonunit/Review/test/itkDivideByConstantImageFilterTest.cxx
      Modules/Nonunit/Review/test/itkMultiplyByConstantImageFilterTest.cxx
      Modules/Nonunit/Review/test/itkReviewHeaderTest.cxx
      Modules/Nonunit/Review/test/itkSubtractConstantFromImageFilterTest.cxx
      Wrapping/WrapITK/Libraries/Review/itkAddConstantToImageFilter.wrap
      Wrapping/WrapITK/Libraries/Review/itkDivideByConstantImageFilter.wrap
      Wrapping/WrapITK/Libraries/Review/itkMultiplyByConstantImageFilter.wrap
      Wrapping/WrapITK/Libraries/Review/itkSubtractConstantFromImageFilter.wrap
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/FFTUseImageAsTemplateParameter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** FFTUseImageAsTemplateParameter.xml
**
** >>>>>>>>>>>>>>>>>>>>>>>>>>>>
** THIS FILE HAS BEEN AUTOMATICALLY GENERATED. EDIT IT BEFORE COMMITING
** <<<<<<<<<<<<<<<<<<<<<<<<<<<
**
**-->
<Change>
    <!--**
    ** Title for the online migration page
    **-->
    <Title>
      F F T Use Image As Template Parameter
    </Title>

    <!--**
    ** The author of the change
    **-->
    <Author>
      GaÃ«tan Lehmann
    </Author>

    <!--**
    ** Date of creation for the XML document
    **-->
    <Date>
      2011-04-07
    </Date>

    <!--**
    ** Plain text description of the change
    ** Extracted from git commit messages
    **-->
    <Description>
      The FFT filters now take an image type as template parameter.
      The FFT filters were using the pixel type and the image dimension
      instead of the usual image type used elsewhere in ITK.

    </Description>

    <!--**
    ** Sample code snippets
    ** Extracted from git diff of changed files in Examples and Testing
    **-->
    <SampleCode>
      <Old>
        typedef itk::VnlFFTRealToComplexConjugateImageFilter &amp;lt;
        WorkPixelType,
        Dimension &gt; FFTFilterType;
        typedef itk::VnlFFTComplexConjugateToRealImageFilter &amp;lt;
        WorkPixelType,
        Dimension &gt; invFFTFilterType;
      </Old>

      <New>
        typedef itk::VnlFFTRealToComplexConjugateImageFilter &amp;lt; WorkImageType &gt; FFTFilterType;
        typedef itk::VnlFFTComplexConjugateToRealImageFilter &amp;lt; ComplexImageType &gt; invFFTFilterType;
      </New>

    </SampleCode>

    <!--**
    ** The change-ids for all commits in the topic branch
    **-->
    <Gerrit-ChangeId>
      Ic4f6c1733ae75173079af4e684a34827dadbd99c
    </Gerrit-ChangeId>

    <!--**
    ** List of all changed files from the topic branch
    **-->
    <FileList>
      Examples/Filtering/FFTDirectInverse.cxx
      Examples/Filtering/FFTDirectInverse2.cxx
      Examples/Filtering/FFTImageFilter.cxx
      Examples/Filtering/FFTImageFilterFourierDomainFiltering.cxx
      Modules/Filtering/FFT/include/itkFFTComplexConjugateToRealImageFilter.h
      Modules/Filtering/FFT/include/itkFFTComplexConjugateToRealImageFilter.txx
      Modules/Filtering/FFT/include/itkFFTRealToComplexConjugateImageFilter.h
      Modules/Filtering/FFT/include/itkFFTRealToComplexConjugateImageFilter.txx
      Modules/Filtering/FFT/include/itkFFTWComplexConjugateToRealImageFilter.h
      Modules/Filtering/FFT/include/itkFFTWComplexConjugateToRealImageFilter.txx
      Modules/Filtering/FFT/include/itkFFTWRealToComplexConjugateImageFilter.h
      Modules/Filtering/FFT/include/itkFFTWRealToComplexConjugateImageFilter.txx
      Modules/Filtering/FFT/include/itkVnlFFTComplexConjugateToRealImageFilter.h
      Modules/Filtering/FFT/include/itkVnlFFTComplexConjugateToRealImageFilter.txx
      Modules/Filtering/FFT/include/itkVnlFFTRealToComplexConjugateImageFilter.h
      Modules/Filtering/FFT/include/itkVnlFFTRealToComplexConjugateImageFilter.txx
      Modules/Filtering/FFT/test/itkFFTWD_FFTTest.cxx
      Modules/Filtering/FFT/test/itkFFTWF_FFTTest.cxx
      Modules/Filtering/FFT/test/itkVnlFFTTest.cxx
      Modules/Filtering/FFT/test/itkVnlFFTWD_FFTTest.cxx
      Modules/Filtering/FFT/test/itkVnlFFTWF_FFTTest.cxx
      Modules/Nonunit/Review/include/itkDirectFourierReconstructionImageToImageFilter.h
      Modules/Nonunit/Review/include/itkDirectFourierReconstructionImageToImageFilter.txx
      Modules/Nonunit/Review/include/itkFFTComplexToComplexImageFilter.h
      Modules/Nonunit/Review/include/itkFFTComplexToComplexImageFilter.txx
      Modules/Nonunit/Review/include/itkFFTWComplexToComplexImageFilter.h
      Modules/Nonunit/Review/include/itkFFTWComplexToComplexImageFilter.txx
      Modules/Nonunit/Review/test/itkDirectFourierReconstructionImageToImageFilterTest.cxx
      Modules/Nonunit/Review/test/itkFFTComplexToComplexImageFilterTest01.cxx
      Modules/Nonunit/Review/test/itkFFTComplexToComplexImageFilterTest02.cxx
      Wrapping/WrapITK/Languages/Python/Tests/FFTImageFilter.py
      Wrapping/WrapITK/Libraries/FFT/itkDirectFourierReconstructionImageToImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFT/itkFFTComplexConjugateToRealImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFT/itkFFTComplexToComplexImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFT/itkFFTRealToComplexConjugateImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFT/itkVnlFFTComplexConjugateToRealImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFT/itkVnlFFTRealToComplexConjugateImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFTW/itkFFTWComplexConjugateToRealImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFTW/itkFFTWComplexToComplexImageFilter.wrap
      Wrapping/WrapITK/Libraries/FFTW/itkFFTWRealToComplexConjugateImageFilter.wrap
    </FileList>

    <!--**
    ** If the migration can be accomplished by a simple string
    ** substitution, then use the following construct to define
    ** the substitution rule.
    **
    ** <MigrationFix-Automatic>
    **   <Old>
    **     MipsleledName
    **   </Old>
    **   <New>
    **     MisspelledName
    **   </New>
    ** </MigrationFix-Automatic>
    **-->

    <!--**
    ** If the migration can NOT be accomplished by a simple string
    ** substitution, but potential problem spots can be identified,
    ** use the following construct to define a migration flag rule.
    **
    ** <MigrationFix-Manual>
    **   OldFunctionName
    ** </MigrationFix-Manual>
    **-->

</Change>

=== picslITK/ITK4_topics/Documentation/Migration/RealTimeClockAPIChanges.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Change SYSTEM "http://ij.itk.org/itkfaq/ITKMigration.dtd">
<!--**
**
** RealTimeClockAPIChanges.xml
**
**-->
<Change>
  <!--**
      ** RealTimeClock API Changes
      **-->
  <Title>
    GetTimeStamp is now private
  </Title>

  <Author>
  Luis Ibanez
  </Author>

  <!--**
      ** Plain text description of the change
      **-->
  <Description>
    The GetTimeStamp method is now private. It returns the modified
    time of the object. In prior versions, GetTimeStamp() was public
    and returned the time in seconds.
  </Description>

  <!--**
      ** Sample code snippets
      **-->
  <SampleCode>
    <Old>
      <![CDATA[
      #include "itkRealTimeClock.h"
      itk::RealTimeClock::Pointer clock = itk::RealTimeClock::New();
      double timeStart = clock->GetTimeStamp();
      ]]>
    </Old>
    <New>
      <![CDATA[
      #include "itkRealTimeClock.h"
      itk::RealTimeClock::Pointer clock = itk::RealTimeClock::New();
      itk::RealTimeClock::TimeStampType timeStart = clock->GetTimeInSeconds();
      ]]>
    </New>
  </SampleCode>

  <!--**
      ** The change-ids for all commits in the topic branch
      **-->
  <Gerrit-ChangeId>
    Ibef22c3e4cc0c45a2755289672c13d386e8096b4
  </Gerrit-ChangeId>

  <!--**
      ** List of all changed files from the topic branch
      **-->
  <FileList>
    Code/Common/itkRealTimeClock.h
    Code/Common/itkRealTimeClock.cxx
  </FileList>

<MigrationFix-Automatic>
  <Old>
    GetTimeStamp
  </Old>
  <New>
    GetTimeInSeconds
  </New>
</MigrationFix-Automatic>

</Change>
